development:
  # Development environment variables
  database: "postgres://tracker:tracker@127.0.0.1/tracker"
staging:
  # Staging environment variables
production:
  # Production environment variables