datastore:
    host: localhost:27017
    jobs: itrack-jobs
    sessions: itrack-sessions
    models: itrack-models
    dbs: ['itrack-jobs', 'itrack-sessions', 'itrack-models']
subscriber_queue: requests